version: '3'
services:
  app:
    container_name: minimalistic-portfolio
    restart: always
    build: .
    ports:
      - 3000:3000
    networks:
      default:
        ipv4_address: ${APP_IP}
    depends_on:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      default:
        ipv4_address: ${MONGO_IP}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      default:
        ipv4_address: ${REDIS_IP}
        
networks:
  default:
    external: true
    name: Minimalistic Portfolio