version: '3'
services:
  app:
    container_name: minimalistic-portfolio
    restart: always
    build: .
    ports:
      - 3000:3000
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    networks:
      - minimalistic-portfolio
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./MongoDB:/data/db
    ports:
      - 27017:27017
    networks:
      - minimalistic-portfolio
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
  redis:
    container_name: redis
    image: redis
    restart: always
    volumes:
      - ./Redis:/data
    ports:
      - 6379:6379
    networks:
      - minimalistic-portfolio
        
networks:
  minimalistic-portfolio:
    driver: bridge